# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a853774c6418721102b4708d08d4a953d04c80cc563e1b14142897651969ccaeaed0edb1e5f53a36cb91651d96904a6658c7957aeefb32c965e427c17941cf

test:
  secret_key_base: 9fec894acb967ef79c0a3d5818fe300b8a4c0c3833a6645e6463d607c280b1a8be146f2edb53d212d96e2d295e5a16275c6ed575e6603fd9ca05fbb3062696a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
